language: python
python:
  # Default version
  - 3.8

  # Also run tests on:
  - 3.5.2
  - 3.5
  - 3.6
  - 3.7
  - 3.9

install:
  - python3 -m pip install -U pytest pytest-cov coveralls
  - sudo apt-get install libxml2-utils

script:
  - python3 -m pip install .
  - test/schema/1685-2014/download_schema.sh
  - test/schema/1685-2009/download_schema.sh
  - cd test
  - pytest --cov=peakrdl

after_success:
  - coveralls

stages:
  - test
  # Only execute deployment stage on tagged release commits in the form of "v1.2.3"
  # and from your repository (e.g. not PRs).
  # Also allows alpha/beta releases such as "v1.2.3b2"
  - name: deploy
    if: repo = SystemRDL/PeakRDL-ipxact AND tag =~ ^v\d+\.\d+\.\w+$

jobs:
  include:
    # Run lint
    - name: Lint
      install:
        - python3 -m pip install pylint
        - python3 -m pip install .
      script: pylint --rcfile test/pylint.rc peakrdl

    # Run static type checking
    - name: Type Check
      install:
        - python3 -m pip install mypy
      script: mypy --config-file test/mypy.ini peakrdl

    # Deploy source distribution
    - stage: deploy
      name: Deploy source distribution
      script: python3 setup.py sdist --formats=gztar
      after_success:
        - python3 -m pip install twine
        - python3 -m twine upload --skip-existing dist/*.tar.gz
